stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - shell
    - ql-dev
  artifacts:
    paths:
      - out
  script: 
    - dotnet publish -c Release -o out QuartierLatin.Backend

deploy:
  stage: deploy
  tags:
    - shell
    - ql-dev
  dependencies:
    - build
  only: 
    - develop
  script: 
    - sudo systemctl stop quartier-admin
    - rm -rf /apps/quartier-admin/app/ && cp -r out/ /apps/quartier-admin/app/
    - sudo systemctl start quartier-admin
