stages:
  - build
#  - test
  - deploy

build:
  stage: build
  tags:
    - shell
    - ql-dev
  artifacts:
    paths:
      - out
  script: 
    - dotnet publish -c Release -o out QuartierLatin.Backend

deploy_dev:
  stage: deploy
  only: 
    - develop
  variables:
    Q_ENV: development
  trigger: quartier-latin/dev-deployment

#tests:
#  stage: test
#  script: 
#    - dotnet run -c Release QuartierLatin.Backend.Tests

deploy:
  stage: deploy
  tags:
    - shell
    - ql-dev
  dependencies:
    - build
  only: 
    - master
  script: 
    - sudo systemctl stop quartier-admin
    - rm -rf /apps/quartier-admin/app/ && cp -r out/ /apps/quartier-admin/app/
    - sudo systemctl start quartier-admin
